// Mock for monaco-editor to avoid issues in Jest tests
const editorInstance = {
  getValue: jest.fn(() => ''),
  setValue: jest.fn(),
  getModel: jest.fn(() => ({
    getValue: jest.fn(() => ''),
    setValue: jest.fn(),
    getFullModelRange: jest.fn(() => ({})),
    getValueLength: jest.fn(() => 0),
    getLineCount: jest.fn(() => 1),
    getLineMaxColumn: jest.fn(() => 1),
    getVersionId: jest.fn(() => 0),
    getLinesContent: jest.fn(() => ['']),
    getOffsetAt: jest.fn(() => 0),
    getWordAtPosition: jest.fn(() => null),
    getWordUntilPosition: jest.fn(() => ({ word: '', startColumn: 1, endColumn: 1 })),
    deltaDecorations: jest.fn(() => []),
    uri: { path: 'test' },
    id: 'test-model-id',
    dispose: jest.fn(),
    onDidChangeContent: jest.fn(() => ({ dispose: jest.fn() })),
  })),
  setModel: jest.fn(),
  dispose: jest.fn(),
  onDidChangeModelContent: jest.fn(() => ({ dispose: jest.fn() })),
  onDidChangeCursorPosition: jest.fn(() => ({ dispose: jest.fn() })),
  onKeyDown: jest.fn(() => ({ dispose: jest.fn() })),
  onDidFocusEditorWidget: jest.fn(() => ({ dispose: jest.fn() })),
  onDidBlurEditorWidget: jest.fn(() => ({ dispose: jest.fn() })),
  saveViewState: jest.fn(() => null),
  restoreViewState: jest.fn(),
  updateOptions: jest.fn(),
  getOption: jest.fn(() => false),
  executeEdits: jest.fn(),
  pushUndoStop: jest.fn(),
  focus: jest.fn(),
  addAction: jest.fn(() => ({ dispose: jest.fn() })),
  addCommand: jest.fn(),
  getDomNode: jest.fn(() => document.createElement('div')),
  getPosition: jest.fn(() => ({ lineNumber: 1, column: 1 })),
  setPosition: jest.fn(),
  revealLine: jest.fn(),
  deltaDecorations: jest.fn(() => []),
  createContextKey: jest.fn(() => ({ set: jest.fn(), get: jest.fn(), reset: jest.fn() })),
  trigger: jest.fn(),
  layout: jest.fn(),
  onDidContentSizeChange: jest.fn(() => ({ dispose: jest.fn() })),
  onDidFocusEditorText: jest.fn(() => ({ dispose: jest.fn() })),
  getContentHeight: jest.fn(() => 100),
  addKeybindingRule: jest.fn(),
  setScrollPosition: jest.fn(),
  getScrollHeight: jest.fn(() => 0),
  getScrollTop: jest.fn(() => 0),
  setScrollTop: jest.fn(),
  getAction: jest.fn(() => ({ run: jest.fn() })),
};

const monaco = {
  editor: {
    create: jest.fn(() => editorInstance),
    createModel: jest.fn(() => editorInstance.getModel()),
    defineTheme: jest.fn(),
    setModelMarkers: jest.fn(),
    getModel: jest.fn(),
    createDiffEditor: jest.fn(),
    onDidCreateEditor: jest.fn(() => ({ dispose: jest.fn() })),
    tokenize: jest.fn(() => []),
    setTheme: jest.fn(),
    getModelMarkers: jest.fn(() => []),
    onDidChangeMarkers: jest.fn(() => ({ dispose: jest.fn() })),
    remeasureFonts: jest.fn(),
    addKeybindingRule: jest.fn(),
    addKeybindingRules: jest.fn(),
    EditorOption: { readOnly: 0 },
    ColorScheme: { DARK: 2, LIGHT: 1, HIGH_CONTRAST_DARK: 3, HIGH_CONTRAST_LIGHT: 4 },
  },
  languages: {
    register: jest.fn(),
    setMonarchTokensProvider: jest.fn(),
    setLanguageConfiguration: jest.fn(),
    registerCompletionItemProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerHoverProvider: jest.fn(() => ({ dispose: jest.fn() })),
    setModelLanguage: jest.fn(),
    CompletionItemKind: { Function: 1, Variable: 2, Keyword: 13 },
    CompletionItemInsertTextRule: { InsertAsSnippet: 4 },
  },
  KeyMod: { CtrlCmd: 2048, Shift: 1024, Alt: 512 },
  KeyCode: { Enter: 3, Escape: 9, F1: 59, Home: 14, End: 13, UpArrow: 16, DownArrow: 18, Tab: 2 },
  Range: jest.fn(() => ({ startLineNumber: 0, endLineNumber: 0, startColumn: 0, endColumn: 0 })),
  Uri: { parse: jest.fn((s: string) => ({ path: s })), file: jest.fn() },
  MarkerSeverity: { Error: 8, Warning: 4, Info: 2, Hint: 1 },
  Token: jest.fn(),
};

module.exports = monaco;
